### ISSUE TITLE
Attribute Error in netfields based lookup after updating to 1.4.0

### ISSUE THREAD

**Issue by sevdog** [jimfunk/django-postgresql-netfields#135]
In one of my project I have the following setup which is used to hold in the same column a value which can be an hostname or an IP address

```python
from django.db.models import CharField, Transform, Model
from django.db.models.functions import Cast
from netfields.fields import InetAddressField


class MultiValueField(CharField):
    """Wrapper on base ``django.db.model.CharField`` to support to-inet transform."""


@MultiValueField.register_lookup
class ToInet(Cast, Transform):
    """Transform to force value to be casted as ``inet``"""

    lookup_name = 'to_inet'

    def __init__(self, expression):
        super().__init__(expression, InetAddressField())


class NetworkProperty(models.Model):
   value = MultiValueField(max_length=255)


```

After updating to 1.4.0 I get the following error when using `NetworkProperty.objects.filter(value__to_inet='192.168.1.1')`:

<details>
<summary> <code>AttributeError: 'InetAddressField' object has no attribute 'model'</code> </summary>

```
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../.venv/lib/python3.13/site-packages/django/db/models/query.py:386: in __iter__
    self._fetch_all()
../.venv/lib/python3.13/site-packages/django/db/models/query.py:1954: in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../.venv/lib/python3.13/site-packages/django/db/models/query.py:273: in __iter__
    for row in compiler.results_iter(
../.venv/lib/python3.13/site-packages/django/db/models/sql/compiler.py:1572: in results_iter
    results = self.execute_sql(
../.venv/lib/python3.13/site-packages/django/db/models/sql/compiler.py:1610: in execute_sql
    sql, params = self.as_sql()
                  ^^^^^^^^^^^^^
../.venv/lib/python3.13/site-packages/django/db/models/sql/compiler.py:794: in as_sql
    self.compile(self.where) if self.where is not None else ("", [])
    ^^^^^^^^^^^^^^^^^^^^^^^^
../.venv/lib/python3.13/site-packages/django/db/models/sql/compiler.py:577: in compile
    sql, params = node.as_sql(self, self.connection)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../.venv/lib/python3.13/site-packages/django/db/models/sql/where.py:151: in as_sql
    sql, params = compiler.compile(child)
                  ^^^^^^^^^^^^^^^^^^^^^^^
../.venv/lib/python3.13/site-packages/django/db/models/sql/compiler.py:577: in compile
    sql, params = node.as_sql(self, self.connection)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../.venv/lib/python3.13/site-packages/django/db/models/lookups.py:426: in as_sql
    return super().as_sql(compiler, connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../.venv/lib/python3.13/site-packages/django/db/models/lookups.py:258: in as_sql
    rhs_sql, rhs_params = self.process_rhs(compiler, connection)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../.venv/lib/python3.13/site-packages/django/db/models/lookups.py:141: in process_rhs
    return self.get_db_prep_lookup(value, connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../.venv/lib/python3.13/site-packages/django/db/models/lookups.py:291: in get_db_prep_lookup
    else get_db_prep_value(v, connection, prepared=True)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

    def get_db_prep_value(self, value, connection, prepared=False):
        if value is None:
            return None
    
>       if self.model._meta.get_field(self.name).get_internal_type() == 'ArrayField':
           ^^^^^^^^^^
E       AttributeError: 'InetAddressField' object has no attribute 'model'

../.venv/lib/python3.13/site-packages/netfields/fields.py:97: AttributeError
```
</details>

Which is caused by the change in f7529f2 in which was removed the check that `self.model` was present, because in this case che `output_field` does not receive any "model".

If I try to set the model from LHS, which is the real model field, it will trigger a `FieldDoesNotExist: NetworkProperty has no field named 'None'` because neither the `name` attribute is set in this scenario.

**Comment by jimfunk** [comment]
I think the only way you can have such a field is when the underlying column is char or text. The netfields fields are expecting native INET/CIDR fields. I would expect a lot of things to break, especially lookups if that is not the case.

**Comment by sevdog** [comment]
This "trick" was very usefult to me to leverage on netfields lookups for my field (when I am sure that the contained value can be trasformed to an INET) to perform: `.filter(value__to_inet__net_contained=...)`.

With the current code I should do:

```
from django.db.models.functions import Cast
from netfields import InetAddressField

NetworkProperty.annotate(inet_val=Case('value', InetAddressField())).filter(inet_val__net_contained=...)
```

which is much more verbose.

**Comment by jimfunk** [comment]
Right, but the fact that it worked before was a fluke as it depended on a workaround for array handling in an ancient version on Django.

The second may be more verbose, but it is idiomatic Django.

**Comment by sevdog** [comment]
Ok, I will put on an utility method to avoid repeating the same boilerplate in every point in which I was using the lookup.
